// Generator for AdvancedTabContent.tsx
const fs = require("fs");
const path = require("path");

const target = "C:/Users/Shubh Varshney/Downloads/agentic-signal/client/src/components/nodes/LlmProcessNode/AdvancedTabContent.tsx";

const content = [
'/************************************************************************',
' *    Copyright (C) 2025 Code Forge Temple                              *',
' *    This file is part of agentic-signal project                       *',
' *    See the LICENSE file in the project root for license details.     *',
' ************************************************************************/',
'',
'/* eslint-disable max-len */',
'',
'import { Box, Checkbox, FormControlLabel, FormGroup, Slider, Switch, Typography } from "@mui/material";',
'import { PipelineStage } from "./types/workflow";',
'',
'const ADVANCED_STAGES: PipelineStage[] = ["classifier", "extractor", "generator", "validator"];',
'',
'export function getAdvancedTabContent(',
'    pipelineMode: any,',
'    consistencyMode: any,',
'    fallbackMode: any,',
'    id: string,',
'    onConfigChange: (id: string, config: Record<string, any>) => void',
') {',
'    const pm = pipelineMode ?? { enabled: false, stages: [...ADVANCED_STAGES] };',
'    const cm = consistencyMode ?? { enabled: false, runs: 3 };',
'    const fm = fallbackMode ?? { enabled: false };',
'',
'    return (',
'        <Box sx={{ p: 2, overflow: "auto" }}>',
'            <Typography variant="subtitle1" fontWeight={600} gutterBottom>',
'                Multi-Pass Pipeline',
'            </Typography>',
'            <Typography variant="body2" color="text.secondary" gutterBottom>',
'                Breaks complex tasks into 4 narrow micro-tasks small models handle.',
'            </Typography>',
'            <FormGroup>',
'                <FormControlLabel',
'                    control={',
'                        <Switch',
'                            checked={pm.enabled}',
'                            onChange={(e) =>',
'                                onConfigChange(id, {',
'                                    pipelineMode: { enabled: e.target.checked, stages: pm.stages },',
'                                })',
'                            }',
'                        />',
'                    }',
'                    label="Enable Multi-Pass Pipeline"',
'                />',
'                {pm.enabled && (',
'                    <Box sx={{ ml: 3, mt: 1 }}>',
'                        {ADVANCED_STAGES.map((stage) => (',
'                            <FormControlLabel',
'                                key={stage}',
'                                control={',
'                                    <Checkbox',
'                                        size="small"',
'                                        checked={pm.stages.includes(stage)}',
'                                        onChange={(e) => {',
'                                            const stages = e.target.checked',
'                                                ? [...pm.stages, stage]',
'                                                : pm.stages.filter((s) => s !== stage);',
'                                            onConfigChange(id, { pipelineMode: { ...pm, stages } });',
'                                        }}',
'                                    />',
'                                }',
'                                label={stage.charAt(0).toUpperCase() + stage.slice(1)}',
'                            />',
'                        ))}',
'                    </Box>',
'                )}',
'            </FormGroup>',
'',
'            <Box sx={{ mt: 3 }}>',
'                <Typography variant="subtitle1" fontWeight={600} gutterBottom>',
'                    Self-Consistency Voting',
'                </Typography>',
'                <Typography variant="body2" color="text.secondary" gutterBottom>',
'                    Runs prompt multiple times and picks consensus best output.',
'                </Typography>',
'                <FormControlLabel',
'                    control={',
'                        <Switch',
'                            checked={cm.enabled}',
'                            onChange={(e) =>',
'                                onConfigChange(id, {',
'                                    consistencyMode: { enabled: e.target.checked, runs: cm.runs },',
'                                })',
'                            }',
'                        />',
'                    }',
'                    label="Enable Consistency Voting"',
'                />',
'                {cm.enabled && (',
'                    <Box sx={{ ml: 3, mt: 1 }}>',
'                        <Typography variant="body2" gutterBottom>',
'                            Runs: {cm.runs}',
'                        </Typography>',
'                        <Slider',
'                            size="small"',
'                            min={2}',
'                            max={5}',
'                            step={1}',
'                            value={cm.runs}',
'                            onChange={(_e, value) =>',
'                                onConfigChange(id, {',
'                                    consistencyMode: { enabled: true, runs: value as number },',
'                                })',
'                            }',
'                            marks={[',
'                                { value: 2, label: "2" },',
'                                { value: 3, label: "3" },',
'                                { value: 5, label: "5" },',
'                            ]}',
'                            sx={{ maxWidth: 200 }}',
'                        />',
'                    </Box>',
'                )}',
'            </Box>',
'',
'            <Box sx={{ mt: 3 }}>',
'                <Typography variant="subtitle1" fontWeight={600} gutterBottom>',
'                    Progressive Fallback',
'                </Typography>',
'                <Typography variant="body2" color="text.secondary" gutterBottom>',
'                    Handles 68% of requests with deterministic rules before LLM.',
'                </Typography>',
'                <FormControlLabel',
'                    control={',
'                        <Switch',
'                            checked={fm.enabled}',
'                            onChange={(e) =>',
'                                onConfigChange(id, { fallbackMode: { enabled: e.target.checked } })',
'                            }',
'                        />',
'                    }',
'                    label="Enable Progressive Fallback"',
'                />',
'            </Box>',
'        </Box>',
'    );',
'}',
'',].join('\n');

fs.writeFileSync(target, content);
console.log("AdvancedTabContent.tsx rewritten successfully");